### ISSUE TITLE
Missing folders and files? 

### ISSUE THREAD

**Issue by jonmatthis** [raultrades/SMA-outfits#1]
Hello! Your README references various folders and files, but the only files in your repo appear to be `README,md` and `LICENSE`

![image](https://github.com/raultrades/SMA-outfits/assets/15314521/46dcf835-b262-4821-81fc-143b0d1ce194)

Am I missing something, or did the other files not get uploaded somehow? 

I saw you on TT, and it sounds like you might be kinda new to GH - let me know if you need a hand getting set up :)

**Comment by luciademoja** [comment]
@raultrades I can't see any folders either, how am I supposed to test this without any code?

**Comment by ivantan-ys** [comment]
Are there supposed to be files/folders as stated in the README, or is this everything?

**Comment by ataseen** [comment]
I don't see the files either. How can we have public attention and exposure to this matter when pertinent files are missing?

**Comment by raultrades** [comment]
Publishing actionable code will effectively result in being charged with market manipulation and conspiracy to manipulate the U.S. Stock Market.

In the readme, it’s just the raw data (i.e. associated parameter limitations, specific calculable outfits, defining systems, and real time case studies that link back to all of the threads on the page).  If I could evade legalese and share actionable code... I would.

Since the OHLC/Outfit data is a critical component of detection systems it can get construed as an act of conspiracy. Given the weight of the info I can be tried against CFAA laws positing any code and posting it. I would effectively lose all of my current legal representation navigating whistleblower protections.  That’s not a bullet I’m prepared to take in the current legal landscape. I'm not a bank or institution, I'm just a data analyst.
