### ISSUE TITLE
Lack of credibility

### ISSUE THREAD

**Issue by vxld100** [raultrades/SMA-outfits#3]
Given the grandiosity of your claims, your repository would benefit from greater rigour in presenting your ideas. Consider this a peer-review of the content you have published. Out of respect for the effort you have put in, I will be completely honest with you. Here are some issues that stand out:

1. **Lack of citations.** If your work is to get at least any consideration from a technical and scientifically minded community, you will need to back up your assumptions and any other outside information you use. This is not case as of now.
2. **Lack of theoretical background.** If your claims ought to have any scientific value, they must fit into a well-defined theoretical framework. Any evidence is only evidence if it disproves a certain hypothesis. Your work doesn't lay out what the market would look like without the manipulation you allege. Hence, your observations cannot be interpreted. You do a good job at laying out some necessary definitions, but that is not a theoretical embedding. 
3. **Lack of evidence.** Right now you are alleging a huge conspiracy based on some very short and unclear interpretations of graphs. Your analysis would hugely benefit from quantitative results. There are no statistics to be found in your work. This is a huge issue, as one could allege that you are drawing arbitrary conclusions. This is very important because the analysis of graphs already is very controversial, and has a rather poor reputation in the finance community and academia. 
4. **Lack of expertise.** In theory anyone can make discoveries across disciplines. Science is not a matter of human authority. But since you come from a background that is very different from the subject matter, you might want to provide some explanation of how you came to possess whatever knowledge of finance you currently possess.
5. **Accusatory tone.** Both your case studies and your repository as a whole suffer from an accusatory tone, which takes credibility away from your analysis. That is because it gives the impression that you are driven by politically motivated self-interest or alarmist social media fame seeking in drawing conclusion instead of objective measures.

Don't let my words stop your enthusiasm. These are just recommendations that will turn the looks of this repository from a conspiracy theory to a document worth analysing.

**Comment by raultrades** [comment]
Whistleblower networks will not work with me if I post code which is what I was planning on doing. It’s because regulators can accuse me (and them) of unintentionally facilitating market manipulation given the platform is increasing every day.

In the readme is the raw data (i.e. associated parameter limitations, specific calculable outfits, defining systems, and real time case studies that link back to the threads on the page).
Be sure to read top to bottom from the intro!

It's inappropriate to apply any other methodology or practice outside of what it outlined in the repository's readme which is what makes what's shared here quite significant. I can also assure you any push toward inflammatory responses were for media investigations. Regulators did not care about what I was sharing on social media until there was public reception. I hope the consistent and taped case studies can serve as insight for the public that would otherwise never have access to high grade and real time analysis.

**Comment by vxld100** [comment]
@raultrades You will definitely not get accused of anything if you post code that shows some kind of unusual pattern in trading activity, or some more concrete results about it. Uncovering a conspiracy does not equate with reproducing the tools they use. Also, stop calling your X threads data. It is not numeric, neither comprehensive, nor properly analyzed.
